<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="JobRouteCard.aspx.cs" Inherits="administrator.JobRouteCard" %>
<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
<div>
<fieldset>
<legend>Job Route Card</legend>
<table>
<tr>
<td>
    <asp:Label ID="Label1" runat="server" Text="Job card No"></asp:Label>
</td>
<td>
    <asp:TextBox ID="TextBox1" runat="server"></asp:TextBox>
</td>
<td>
    <asp:Label ID="Label2" runat="server" Text="Job card date"></asp:Label>
</td>
<td>
    <asp:TextBox ID="TextBox2" runat="server" TextMode="Date"></asp:TextBox>
</td>
<td>
    <asp:Label ID="Label3" runat="server" Text="SOP/MAO No"></asp:Label>
</td>
<td>
    <asp:TextBox ID="TextBox3" runat="server"></asp:TextBox>
</td>
<td>
    <asp:Label ID="Label4" runat="server" Text="SOP/MAO Date"></asp:Label>
</td>
<td>
    <asp:TextBox ID="TextBox4" runat="server" TextMode="Date"></asp:TextBox>
</td>
</tr>
<tr>
<td>
    <asp:Label ID="Label5" runat="server" Text="Job type"></asp:Label>
</td>
<td>
    <asp:TextBox ID="TextBox5" runat="server"></asp:TextBox>
</td>
<td>
    <asp:Label ID="Label6" runat="server" Text="Party code"></asp:Label>
</td>
<td>
    <asp:TextBox ID="TextBox6" runat="server"></asp:TextBox>
</td>
<td>
    <asp:Label ID="Label7" runat="server" Text="Party name"></asp:Label>
</td>
<td>
    <asp:TextBox ID="TextBox7" runat="server"></asp:TextBox>
</td>
<td>
    <asp:Label ID="Label8" runat="server" Text="Item code"></asp:Label>
</td>
<td>
    <asp:TextBox ID="TextBox8" runat="server"></asp:TextBox>
</td>
</tr>
<tr>
<td>
    <asp:Label ID="Label9" runat="server" Text="Item name"></asp:Label>
</td>
<td>
    <asp:TextBox ID="TextBox9" runat="server"></asp:TextBox>
</td>
<td>
    <asp:Label ID="Label10" runat="server" Text="Unit"></asp:Label>
</td>
<td>
    <asp:TextBox ID="TextBox10" runat="server"></asp:TextBox>
</td>
<td>
    <asp:Label ID="Label11" runat="server" Text="Balance Qty"></asp:Label>
</td>
<td>
    <asp:TextBox ID="TextBox11" runat="server"></asp:TextBox>
</td>
<td>
    <asp:CheckBox ID="CheckBox1" runat="server" Text="Complete Y/N" />
</td>
</tr>
</table>
</fieldset>
<fieldset>
<legend>Production Details</legend>
<table>
<tr>
<td>
    <asp:Label ID="Label12" runat="server" Text="Job card Qty (Qty)"></asp:Label>
</td>
<td>
    <asp:TextBox ID="TextBox12" runat="server"></asp:TextBox>
</td>
<td>
    <asp:Label ID="Label13" runat="server" Text="Expected Produce Time [in hours]"></asp:Label>
</td>
<td>
    <asp:TextBox ID="TextBox13" runat="server" TextMode="Time"></asp:TextBox>
</td>
<td>
    <asp:Label ID="Label14" runat="server" Text="Commitment Delivery Date"></asp:Label>
</td>
<td>
    <asp:TextBox ID="TextBox14" runat="server" TextMode="Date"></asp:TextBox>
</td>
</tr>
<tr>
<td>
    <asp:Label ID="Label15" runat="server" Text="Remarks Note (by production)"></asp:Label>
</td>
<td>
    <asp:TextBox ID="TextBox15" runat="server" TextMode="MultiLine"></asp:TextBox>
</td>
<td>
    <asp:Label ID="Label16" runat="server" Text="Generated By"></asp:Label>
</td>
<td>
    <asp:TextBox ID="TextBox16" runat="server"></asp:TextBox>
</td>
<td>
    <asp:Label ID="Label17" runat="server" Text="Approved by"></asp:Label>
</td>
<td>
    <asp:TextBox ID="TextBox17" runat="server"></asp:TextBox>
</td>
</tr>
</table>
</fieldset>
<fieldset>
<legend>Production Process Detail</legend>
    <asp:GridView ID="GridView1" runat="server">
    <Columns>
    <asp:BoundField HeaderText="Process/Batch No" />
     <asp:BoundField HeaderText="Process Name" />
      <asp:BoundField HeaderText="Pro. Flow No" />
 <asp:BoundField HeaderText="Load Quality" />
 <asp:BoundField HeaderText="Prod. Qty" />
 <asp:BoundField HeaderText="Balance Qty" />
    </Columns>
    </asp:GridView>
</fieldset>
<fieldset>
<legend>Production Detail</legend>
    <asp:GridView ID="GridView2" runat="server">
    <Columns>
     <asp:BoundField HeaderText="Process Name" />
     <asp:BoundField HeaderText="Production Date" />
     <asp:BoundField HeaderText="Time In" />
     <asp:BoundField HeaderText="Time Out" />
     <asp:BoundField HeaderText="Prod. Qty" />
     <asp:BoundField HeaderText="Rejected Qty" />
     <asp:BoundField HeaderText="QC. Qty" />
     <asp:BoundField HeaderText="Move to process" />

    </Columns>
    </asp:GridView>
</fieldset>
<table>
<tr>
<td>
    <asp:Button ID="Button1" runat="server" Text="RM Consumption" />
</td>
<td>
    <asp:Button ID="Button2" runat="server" Text="Daily production entry" />
</td>
<td>
    <asp:Button ID="Button3" runat="server" Text="Demand Material Slip" />
</td>
<td>
    <asp:Button ID="Button4" runat="server" Text="Save" />
</td>
<td>
    <asp:Button ID="Button5" runat="server" Text="Cancel" />
</td>
</tr>
</table>
</div>
</asp:Content>
